"""Device-agnostic analysis core (pure functions, no I/O, no GUI)."""

from magnetics.core.mode_shape import (
    GPFitResult,
    ModeShapeResult,
    ModeTrackResult,
    gp_mode_shape,
    gp_periodic_fit,
    mac,
    mac_n_spectrum,
    mode_pattern_2d,
    periodic_kernel,
    shape_noise,
    shape_vector,
    track_mode_shape,
)
from magnetics.core.spectral import (
    CrossSpectrumResult,
    ModeAtFrequencyResult,
    SpectrogramResult,
    ToroidalFitResult,
    compute_spectrogram,
    cross_spectrum,
    denoise_spectrogram,
    downsample,
    extract_mode_at_frequency,
    fit_toroidal_mode,
    integrate_bdot,
    stft_layout,
)

__all__ = [
    "CrossSpectrumResult",
    "GPFitResult",
    "ModeAtFrequencyResult",
    "ModeShapeResult",
    "ModeTrackResult",
    "SpectrogramResult",
    "ToroidalFitResult",
    "compute_spectrogram",
    "cross_spectrum",
    "denoise_spectrogram",
    "downsample",
    "extract_mode_at_frequency",
    "fit_toroidal_mode",
    "gp_mode_shape",
    "gp_periodic_fit",
    "integrate_bdot",
    "mac",
    "mac_n_spectrum",
    "mode_pattern_2d",
    "periodic_kernel",
    "shape_noise",
    "shape_vector",
    "stft_layout",
    "track_mode_shape",
]
